modelcanvas/urls.py
# -*- encoding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'modelcanvas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT}),

    url(r'^$', 'main.views.home', name='home'),
    url(r'^novo_negocio/$', 'main.views.novo_negocio', name='novo_negocio'),
    url(r'^listar_negocio/$', 'main.views.listar_negocio', name='listar_negocio'),
    url(r'^exibir_negocio/(?P<nid>\d+)/$', 'main.views.exibir_negocio', name='exibir_negocio'),
    url(r'^editar_negocio/(?P<nid>\d+)/$', 'main.views.editar_negocio', name='editar_negocio'),
    url(r'^excluir_negocio/(?P<nid>\d+)/$', 'main.views.excluir_negocio', name='excluir_negocio'),

    url(r'^teste/$', 'main.views.teste', name='teste'),
)

main/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.utils.encoding import smart_text

# Create your models here.
class Negocio (models.Model):
    nome = models.CharField(max_length=80)
    autor = models.CharField(max_length=80)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    proposta_valor = models.CharField(max_length=80, null=True, blank=True)
    parceiros_chave = models.CharField(max_length=80, null=True, blank=True)
    atividades_chave = models.CharField(max_length=80, null=True, blank=True)
    recursos_chave = models.CharField(max_length=80, null=True, blank=True)
    relacionamento_clientes = models.CharField(max_length=80, null=True, blank=True)
    segmentos_clientes = models.CharField(max_length=80, null=True, blank=True)
    canais = models.CharField(max_length=80, null=True, blank=True)
    estrutura_custos = models.CharField(max_length=80, null=True, blank=True)
    fontes_receita = models.CharField(max_length=80, null=True, blank=True)

    def __unidode__(self):
        return self.nome + ' - ' + self.autor

    class Meta:
        verbose_name = "Negócio"
        verbose_name_plural = "Negócios"

main/forms.py
# -*- encoding: utf-8 -*-
from django.forms import ModelForm
from django.forms.extras.widgets import *

from main.models import Negocio

# forms
class FormProposta(ModelForm):
    class Meta:
        model = Negocio
        exclude = ['criado', 'atualizado',]
        


main/views.py
# -*- encoding: utf-8 -*-

# python import
import datetime

# django import
from django.http import HttpResponse
from django.template import RequestContext

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render_to_response

from main.forms import FormProposta
from main.models import Negocio

# Create your views here.
def teste (request):
    form = FormProposta()
    return render_to_response('teste.html', {'form': form, }, context_instance=RequestContext(request))


def home (request):
    # import pdb; pdb.set_trace()
    return render_to_response('index.html')

def novo_negocio (request):
    # import pdb; pdb.set_trace()
    if request.POST:
        form = FormProposta(request.POST)
        if form.is_valid():
            negocio = form.save(True)
            return redirect('/exibir_negocio/' + str(negocio.id) +'/')
        else:
            return redirect('/') # to do
    else:
        dct = {
            'form': FormProposta(),
        }

    return render_to_response('novo_negocio.html', dct, context_instance=RequestContext(request))

def listar_negocio (request):
    # import pdb; pdb.set_trace()
    dct = {
        'negocios': Negocio.objects.all(),
    }
    return render_to_response('listar_negocio.html', dct, context_instance=RequestContext(request))

def exibir_negocio (request, nid):
    # import pdb; pdb.set_trace()
    try:
        negocio = Negocio.objects.get(id=nid)
    except:
        return render_to_response('teste-404.html', {}, context_instance=RequestContext(request)) # TO DO: criar pagina de erro para negocio nao encontrado

    dct = {
        'negocio': negocio,
    }
    return render_to_response('exibir_negocio.html', dct, context_instance=RequestContext(request))

def editar_negocio (request, nid):
    # import pdb; pdb.set_trace()
    try:
        negocio = Negocio.objects.get(id=nid)
    except:
        return render_to_response('teste-404.html', {}, context_instance=RequestContext(request)) # TO DO: criar pagina de erro para negocio nao encontrado
    
    if request.POST:
        form = FormProposta(request.POST, instance=negocio)
        if form.is_valid():
            negocio=form.save(True)
            error = u'Alterações salvas com sucesso'
            return redirect('/exibir_negocio/' + str(negocio.id) + '/')
        else:
            error = form.errors
    else:
        form = FormProposta(instance=negocio)
        error = False
        
    dct = {
         'negocio': negocio,
         'action': '/editar_negocio/' + str(negocio.id) + '/',
         'form': form,
         'error': error,
         'submit_value': u'Atualizar',
    }
    return render_to_response('editar_negocio.html', dct, context_instance=RequestContext(request))

def excluir_negocio (request, nid):
    # import pdb; pdb.set_trace()
    try:
        negocio = Negocio.objects.get(id=nid)
    except:
        return render_to_response('teste-404.html', {}, context_instance=RequestContext(request)) # TO DO: criar pagina de erro para negocio nao encontrado

    negocio.delete()
    return redirect('/listar_negocio/')

templates/editar_negocio.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Editar Negocio</title>
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/media/css/bootstrap.css" rel="stylesheet" media="screen and (min-width:801px)">
    <link href="/media/css/bootstrap-mobi.css" rel="stylesheet" media="handheld, screen and (max-width:767px)">
    <link href="/media/css/bootstrap-tab.css" rel="stylesheet" media="screen and (min-width:768px) and (max-width:1280px)">
  

    <script type="text/javascript">
		function getConfirmation(){
			var retVal = confirm("Você está certo disso?");
				if(retVal == true){
					alert("Projeto alterado com sucesso!");
					return true;
				}else{
					alert ("Projeto não alterado!");
					return false;
				}
		}
	</script>
  </head>
  <body>	
        <div class="content"> 
                <div class="header">
               		Editar Negócio </div>
                	<bt>
                    	<bt-home><a href="/"><img src="/media/img/home.png" width="26" height="26"></a></bt-home>
                        <bt-menu><a href="/listar_negocio/"><img src="/media/img/menu.png" width="25" height="25"></a></bt-menu>
                    </bt>
                    <bt-add><a href="/novo_negocio/"><img src="/media/img/add.png" width="25" height="25"></a> </bt-add>
                <div class="cor1">
                <form class="form-horizontal" method="POST" action="{{ action }}">
				{% csrf_token %}
                      <div class="control-group"></br><input type="hidden" value="{{ negocio.nome }}"class="input-large"  id="id_nome" name="nome">
                      <input type="hidden" class="input-small" value="{{ negocio.autor }}" id="id_autor" name="autor">
                      <!-- <input type=" date" class="input-small" placeholder="Data"></div> -->
                      <div class="left">Proposta de Valor</div>
                      <div><textarea rows="7"  id="id_proposta_valor" name="proposta_valor">{{ negocio.proposta_valor }}</textarea>
                      <img src="/media/img/info-.png" id="img-" width="25" height="25" onClick='alert("Que valor proporciona a seus clientes? Que problemas de seus clientes estão solucionados? ")'>
					  </div></div>
				</div>
                <script src="http://code.jquery.com/jquery-latest.js"></script>
                <script src="/media/js/bootstrap.min.js"></script>
                <div class="accordion" id="accordion2">
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-red" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                        Parceiros Chave
                      </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                      <div class="accordion-inner" id="id_parceiro_chave">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.parceiros_chave }}" id="id_parceiros_chave" name="parceiros_chave" class="box_text" maxlength="80">{{ negocio.parceiros_chave }}</textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-red" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                        Atividades Chave</a>
                    </div>
                    <div id="collapseTwo" class="accordion-body collapse">
                      <div class="accordion-inner">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.atividades_chave }}" id="id_atividades_chave" name="atividades_chave" class="box_text" maxlength="80">{{ negocio.atividades_chave }}</textarea>
                      </div>
                    </div>
                  </div>
                  <!-- <div id="collapseOne" class="accordion-body collapse">
                      <div class="accordion-inner">
                        <div><textarea rows="7" id="id_proposta_valor" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div> -->
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-red" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                        Recursos Chave</a>
                    </div>
                    <div id="collapseThree" class="accordion-body collapse">
                      <div class="accordion-inner">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.recursos_chave }}" id="id_recursos_chave" name="recursos_chave" class="box_text" maxlength="80">{{ negocio.recursos_chave }}</textarea>
                      </div>
                    </div>
                  </div>
                  <!-- <div class="accordion-group">
                    <div class="accordion-heading"></div>
                    <div id="collapseThree" class="accordion-body collapse">
                      <div class="accordion-inner">
                       <div><textarea rows="7" id="id_proposta_valor" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div> -->
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-blue" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                        Relacionamento com Clientes</a>
                    </div>
                    <div id="collapseFour" class="accordion-body collapse">
                      <div class="accordion-inner">
						<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.relacionamento_clientes }}" id="id_relacionamento_clientes" name="relacionamento_clientes" class="box_text" maxlength="80">{{ negocio.relacionamento_clientes }}</textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-blue" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
                        Segmentos de Clientes</a>
                    </div>
                    <div id="collapseFive" class="accordion-body collapse">
                      <div class="accordion-inner">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.segmentos_clientes }}" id="id_segmentos_clientes" name="segmentos_clientes" class="box_text" maxlength="80">{{ negocio.segmentos_clientes }}</textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-blue" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">
                        Canais</a>
                    </div>
                    <div id="collapseSix" class="accordion-body collapse">
                      <div class="accordion-inner">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.canais }}" id="id_canais" name="canais" class="box_text" maxlength="80">{{ negocio.canais }}</textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-green" data-toggle="collapse" data-parent="#accordion2" href="#collapseSeven">
                        Estrutura de Custos</a>
                    </div>
                    <div id="collapseSeven" class="accordion-body collapse">
                      <div class="accordion-inner">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.estrutura_custos }}" id="id_estrutura_custos" name="estrutura_custos" class="box_text" maxlength="80">{{ negocio.estrutura_custos }}</textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-green" data-toggle="collapse" data-parent="#accordion2" href="#collapseEight">
                        Fontes de Receita</a>
                    </div>
                    <div id="collapseEight" class="accordion-body collapse">
                      <div class="accordion-inner">
							<img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                        <div><textarea rows="7" value="{{ negocio.fontes_receita }}" id="id_fontes_receita" name="fontes_receita" class="box_text" maxlength="80">{{ negocio.fontes_receita }}</textarea>
                      </div>
                    </div>
                  </div>
					 <div class="all"><button type="submit" class="btn-">Concluir</button></div>
                </form>
          
           <div class="span4"><img src="/media/img/logo_firjan.png" width="284" height="58"></div>    
      		 </div>  
           </div>
    </div>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Model canvas APP</title>
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/media/css/bootstrap.css" rel="stylesheet" media="screen and (min-width:801px)">
    <link href="/media/css/bootstrap-mobi.css" rel="stylesheet" media="handheld, screen and (max-width:767px)">
    <link href="/media/css/bootstrap-tab.css" rel="stylesheet" media="screen and (min-width:768px) and (max-width:1280px)">
  </head>
  <body>
	<div class="container-special"> 
        <div class="content-special"> 
            <div class="title">
                <h2>MODEL CANVAS APP</h2>
                <script src="http://code.jquery.com/jquery-latest.js"></script>
                <script src="js/bootstrap.min.js"></script>
            </div>
                <div class="bt">
                  <a href="/novo_negocio/"><button class="btn btn-large btn-block btn-primary" type="button">Novo Negócio</button></a>
                  <a href ="/listar_negocio/"><button class="btn btn-large btn-block" type="button">Listar Negócios</button></a>
          </div>
      		 <div class="span4"><img src="/media/img/logo_firjan.png" width="284" height="58">
        </div>  
    </div>
</div>
  </body>
</html>

templates/listar_negocio.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Listar Negócio</title>
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/media/css/bootstrap.css" rel="stylesheet" media="screen and (min-width:801px)">
    <link href="/media/css/bootstrap-mobi.css" rel="stylesheet" media="handheld, screen and (max-width:767px)">
    <link href="/media/css/bootstrap-tab.css" rel="stylesheet" media="screen and (min-width:768px) and (max-width:1280px)">
  </head>
  <body>
      
	  <div class="content_card">
       <center>
       </br>
		    {% for negocio in negocios %}   
           <div class="card"> 		     
         	 <a href="/exibir_negocio/{{ negocio.id }}/"><h3><strong>{{ negocio.nome }}</strong></h3>
                <p>{{ negocio.autor }}</p>
                <h4>{{ negocio.criado|date:"SHORT_DATE_FORMAT" }}
				<a href="/excluir_negocio/{{negocio.id }}/" onClick="alert('Projeto excluído com sucesso')"><img src="/media/img/recycle2.png" width="20" height="20" align="right"></a></h4> 
            	 								
          </div>
          
			{% endfor %}
        
  	   </center>
     </div>
   
  </body>
</html>

templates/novo_negocio.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Novo Negocio</title>
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/media/css/bootstrap.css" rel="stylesheet" media="screen and (min-width:801px)">
    <link href="/media/css/bootstrap-mobi.css" rel="stylesheet" media="handheld, screen and (max-width:767px)">
    <link href="/media/css/bootstrap-tab.css" rel="stylesheet" media="screen and (min-width:768px) and (max-width:1280px)">
 
  
  </head>
  <body>

        <div class="content"> 
                 <div class="header">
               		Novo Negócio </div>
                	<div class="bt-"><bt>
                    	<bt-home><a href="/"><img src="/media/img/home.png" width="26" height="26"></a></bt-home>
                        <bt-menu><a href="/listar_negocio/"><img src="/media/img/menu.png" width="25" height="25"></a></bt-menu>
                    </bt>
                    <bt-add><a href="/novo_negocio/"><img src="/media/img/add.png" width="25" height="25"></a> </bt-add></div>
                
                <form class="form-horizontal" action="/novo_negocio/" method="POST">
                      {% csrf_token %}
                     
                      
                <div class="cor1">
                      <div class="control-group"><input type="text" class="input-large" placeholder="Nome" id="id_nome" name="nome">
                      <input type="text" class="input-small" placeholder="Autor" id="id_autor" name="autor">

                      <div class="left">Proposta de Valor</div>
                      <div><textarea rows="7" id="id_proposta_valor" name="proposta_valor"></textarea>
                      <img src="/media/img/info-.png" id="img-" width="25" height="25" onClick='alert("Que valor proporciona a seus clientes? Que problemas de seus clientes estão solucionados? ")'></div></div>
        
                </div>
                <script src="http://code.jquery.com/jquery-latest.js"></script>
                <script src="/media/js/bootstrap.min.js"></script>
                <div class="accordion" id="accordion2">
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-red" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                        Parceiros Chave
                      </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                      <div class="accordion-inner" id="id_parceiro_chave">
                        <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quem são seus parceiros e provedores fundamentais?")'>
                      
                        <div><textarea rows="7" id="id_parceiros_chave" name="parceiros_chave" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-red" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                        Atividades Chave</a>
                    </div>
                   <div id="collapseTwo" class="accordion-body collapse">
                      <div class="accordion-inner">
                       <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("O que deve Saber e fazer?")'>
                        <div><textarea rows="7" id="id_atividades_chave" name="atividades_chave" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <!-- <div id="collapseOne" class="accordion-body collapse">
                      <div class="accordion-inner">
                        <div><textarea rows="7" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div> -->
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-red" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                        Recursos Chave</a>
                    </div>
                    <div id="collapseThree" class="accordion-body collapse">
                      <div class="accordion-inner">
                      <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Que recursos físicos, humanos, intelectuais ou econômicos são essenciais? Coisas Imprescindíveis?")'>
                        <div><textarea rows="7" id="id_recursos_chave" name="recursos_chave" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <!-- <div class="accordion-group">
                    <div class="accordion-heading"></div>
                    <div id="collapseThree" class="accordion-body collapse">
                      <div class="accordion-inner">
                       <div><textarea rows="7" id="id_proposta_valor" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div> -->
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-blue" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                        Relacionamento com Clientes</a>
                    </div>
                    <div id="collapseFour" class="accordion-body collapse">
                      <div class="accordion-inner">
                      <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Que tipo de relacionamento que cada segmento de cliente espera ter para estabelecer e manter sua preferência?")'>
                        <div><textarea rows="7" id="id_relacionamento_clientes" name="relacionamento_clientes" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-blue" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
                        Segmentos de Clientes</a>
                    </div>
                    <div id="collapseFive" class="accordion-body collapse">
                      <div class="accordion-inner">
                       <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Para quem cria valor? Quais são seus clientes mais importantes?")'>
                        <div><textarea rows="7" id="id_segmentos_clientes" name="segmentos_clientes" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-blue" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">
                        Canais</a>
                    </div>
                    <div id="collapseSix" class="accordion-body collapse">
                      <div class="accordion-inner">
                      <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Que meios preferem utilizar seu segmento de mercado? (Ex: Loja física, Virtual) Como estabelecer contato com os clientes?")'>
                        <div><textarea rows="7" id="id_canais" name="canais" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-green" data-toggle="collapse" data-parent="#accordion2" href="#collapseSeven">
                        Estrutura de Custos</a>
                    </div>
                    <div id="collapseSeven" class="accordion-body collapse">
                      <div class="accordion-inner">
                      <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Quais são os custos mais importantes do modelo de negocio (Recursos e Atividades chaves).")'>
                        <div><textarea rows="7" id="id_estrutura_custos" name="estrutura_custos" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle-green" data-toggle="collapse" data-parent="#accordion2" href="#collapseEight">
                        Fontes de Receita</a>
                    </div>
                    <div id="collapseEight" class="accordion-body collapse">
                      <div class="accordion-inner">
                      <img src="/media/img/info.png" id="img" width="25" height="25" onClick='alert("Porque valor os seus clientes realmente estão dispostos a pagar? Como gostariam de pagar?")'>
                        <div><textarea rows="7" id="id_fontes_receita" name="fontes_receita" class="box_text" maxlength="80"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="all"><button type="submit" class="btn-">Concluir</button></div>
                </form>
          
           <div class="span4"><img src="/media/img/logo_firjan.png" width="284" height="58"></div>    
      		 </div>  
           </div>
    </div>

  </body>
</html>

templates/teste-404.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>


body {color: #fff; margin: 0;background: url(img/texture.png) repeat;}
.container {width: 960px;margin:50px auto; text-align: center; font: 13px/22px "Helvetica Neue", Arial, Helvetica, Geneva, sans-serif;color: #000;}



.box {
	background: url(img/404.png) no-repeat 0 0;
	border-bottom: 5px solid #000;
	height: 343px;
	margin-bottom: 25px;
 	padding-bottom: 50px;
}

.cover_pan{
	background: #fff url(img/covers.jpg) repeat 1055px bottom;
	height: 343px;
	margin-left:1px; 
	overflow: hidden;
	position: relative;
	width:99.5%;
	z-index: -1;
	
	-moz-animation-name: pan;
	-moz-animation-duration:40s;
	-moz-animation-iteration-count: infinite;
	-moz-animation-timing-function: linear;
	
	-webkit-animation-name: pan;
	-webkit-animation-duration:40s;
	-webkit-animation-iteration-count: infinite;
	-webkit-animation-timing-function: linear;
}

@-moz-keyframes pan {
	0% {
		background-position: 1338px bottom;
	}
	100% {
		background-position: left bottom;
	}
}

@-webkit-keyframes pan {
	0% {
		background-position: 1338px bottom;
	}
	100% {
		background-position: left bottom;
	}
}


</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Página 404 animada</title>
</head>

<body>
<div class="container">
		<div class="box"><div class="cover_pan"></div></div>


</body>
</html>

templates/teste.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bootstrap 101 Template</title>
    <!-- Bootstrap -->
    <link href="/media/css/bootstrap.css" rel="stylesheet" media="screen">
  </head>
  <body>
  <div class="container-special">
        <div class="content-special"> 
            <div class="title">
                <h2>MODEL CANVAS APP</h2>
                <script src="http://code.jquery.com/jquery-latest.js"></script>
                <script src="js/bootstrap.min.js"></script>
           
		     <form action="/novo_negocio/" method="POST" >
				{% csrf_token %}
				{{ form }}
				<input type="submit" value="salvar" />
			 </form>
      		 <div class="span4"><img src="/media/img/logo_firjan.png" width="284" height="58">
        </div>  
    </div>
 </div>
  </body>
</html>